"""Updated the id schema in the Movies relation to be an integer instead of a text.

Revision ID: 22d304842bf2
Revises: b61545d1486d
Create Date: 2021-10-17 23:20:39.357983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22d304842bf2'
down_revision = 'b61545d1486d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Movies',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('image', sa.VARCHAR(), nullable=True),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('streaming_services', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('testTable',
    sa.Column('integer', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('integer')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('testTable')
    op.drop_table('Movies')
    # ### end Alembic commands ###
