"""Initial migration

Revision ID: 32332ee2debe
Revises: 
Create Date: 2021-09-29 23:22:59.063237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32332ee2debe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mytable',
    sa.Column('integer', sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mytable')
    # ### end Alembic commands ###
