"""empty message

Revision ID: 9ea9edcc6c95
Revises: 22d304842bf2
Create Date: 2021-11-19 18:44:44.620151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ea9edcc6c95'
down_revision = '22d304842bf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Movies', sa.Column('runtime', sa.INTEGER(), nullable=True))
    op.add_column('Movies', sa.Column('rating', sa.DECIMAL(), nullable=True))
    op.add_column('Movies', sa.Column('release_date', sa.VARCHAR(), nullable=True))
    op.add_column('Movies', sa.Column('genres', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Movies', 'genres')
    op.drop_column('Movies', 'release_date')
    op.drop_column('Movies', 'rating')
    op.drop_column('Movies', 'runtime')
    # ### end Alembic commands ###
