"""Second migration

Revision ID: a8585a08d037
Revises: 32332ee2debe
Create Date: 2021-09-29 23:24:33.239054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8585a08d037'
down_revision = '32332ee2debe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testTable',
    sa.Column('integer', sa.Integer(), nullable=True)
    )
    op.drop_table('mytable')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mytable',
    sa.Column('integer', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.drop_table('testTable')
    # ### end Alembic commands ###
